
version: 2

sources:
  - name: ARTIST_RAW
    database: MUSICMESH_ARTIST_DEV
    schema: ADF_SOURCE
    tables: 
      - name: SONG_DETAILS
      - name: SPOTIFY_FEATURES_PYTHON


models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
